# Generated by Django 5.2.14 on 2026-06-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_student_age_student_department_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.CharField(default='BK001', max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default='General', max_length=15),
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(default='In-stock', max_length=8),
        ),
    ]
