# Generated by Django 5.2.14 on 2026-06-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_author_book_available_book_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(default='Available', max_length=8),
        ),
    ]
