# Generated by Django 5.2.14 on 2026-06-30 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='issue_date',
            field=models.DateField(default=datetime.date(2026, 6, 30)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuebook',
            name='return_date',
            field=models.DateField(default=datetime.date(2026, 6, 30)),
            preserve_default=False,
        ),
    ]
