# Generated by Django 5.2.14 on 2026-06-30 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_issuebook_issue_date_issuebook_return_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuebook',
            old_name='book',
            new_name='bookname',
        ),
        migrations.RenameField(
            model_name='issuebook',
            old_name='student',
            new_name='studentname',
        ),
    ]
