# Generated by Django 5.2.14 on 2026-06-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_rename_book_issuebook_bookname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuebook',
            old_name='bookname',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='issuebook',
            old_name='studentname',
            new_name='student',
        ),
    ]
