# Generated by Django 5.2.14 on 2026-06-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_rename_bookname_issuebook_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='student',
            field=models.CharField(max_length=10),
        ),
    ]
