# Generated by Django 5.2.14 on 2026-06-30 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_issuebook_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='book_name',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='student_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.student'),
        ),
    ]
