# Generated by Django 5.2.14 on 2026-06-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_issuebook_book_name_issuebook_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='book_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='student_name',
            field=models.CharField(max_length=100),
        ),
    ]
