# Generated by Django 5.2.14 on 2026-07-01 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_issuebook_book_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuebook',
            name='return_date',
        ),
    ]
