# Generated by Django 5.2.14 on 2026-07-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_remove_issuebook_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
