# Generated by Django 5.2.14 on 2026-07-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_alter_student_age_alter_student_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=15),
        ),
    ]
